Add support for Swift Package Manager
infinum/Japx pull request #42
Opened 2020-10-30 08:11 UTC by RafaelFernandezAlv

Hi.

I developed the support for use this library with Swift Package Manager. Can you merge and generate the tag 3.1.0?

Thanks!

2021-02-22 07:52 UTC, mathaeus commented
Hi, thanks for adding SPM support, is there any update on this? @RafaelFernandezAlv @Truba

2021-03-12 10:47 UTC, rromanchuk commented
@RafaelFernandezAlv using your fork now. No problems, thanks.

2021-08-14 20:58 UTC, rromanchuk commented on Package.swift
> +            targets: ["JapxObjC"])
duplicate with https://github.com/infinum/Japx/pull/42/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR27

2021-08-14 21:01 UTC, rromanchuk requested changes

2021-08-14 21:01 UTC, rromanchuk commented on Package.swift
> +    ],
```suggestion
            targets: ["JapxRxMoya"])
    ],
```

2021-09-02 08:31 UTC, merged